imports:
    - { resource: easyadmin/menu.yml }
    - { resource: easyadmin/user.yml }
    - { resource: easyadmin/article.yml }
    - { resource: easyadmin/article_type.yml }
    - { resource: easyadmin/review.yml }
    - { resource: easyadmin/feedback.yml }

easy_admin:
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'