easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            controller: App\Controller\Admin\ArticleController
            list:
                fields:
                    - id
                    - isPublished
                    - { property: 'cover', type: 'image', base_path: '%app.path.images%' }
                    - title
                    - description
            show:
                fields:
                    - id
                    - isPublished
                    - { property: 'cover', type: 'image', base_path: '%app.path.images%' }
                    - title
                    - description
                    - content
            form:
                fields:
                    - isPublished
                    - title
                    - { property: 'coverFile', type: 'file' }
                    - description
                    - content
        