easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            controller: App\Controller\Admin\ArticleController
            list:
                fields:
                    - id
                    - isPublished
                    - title
                    - description
            form:
                fields:
                    - isPublished